"""esquema inicial

Revision ID: 185c82b95142
Revises: 
Create Date: 2026-07-07 19:30:37.607224

"""
from alembic import op
import sqlalchemy as sa


revision = '185c82b95142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilot_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('empresa', sa.String(), nullable=False),
    sa.Column('segmento', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('volumen_estimado', sa.String(), nullable=True),
    sa.Column('consent_privacidad', sa.Boolean(), nullable=True),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('contacted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash')
    )
    op.create_table('kyc_verifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('subject_document_number', sa.String(), nullable=False),
    sa.Column('subject_document_type', sa.String(), nullable=True),
    sa.Column('liveness_passed', sa.Boolean(), nullable=True),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('reniec_validated', sa.Boolean(), nullable=True),
    sa.Column('reniec_full_name_match', sa.Boolean(), nullable=True),
    sa.Column('sunat_validated', sa.Boolean(), nullable=True),
    sa.Column('aml_status', sa.String(), nullable=True),
    sa.Column('aml_match_details', sa.JSON(), nullable=True),
    sa.Column('selfie_storage_key', sa.String(), nullable=True),
    sa.Column('document_photo_storage_key', sa.String(), nullable=True),
    sa.Column('overall_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_charge_id', sa.String(), nullable=True),
    sa.Column('amount_pen', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signature_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('signer_name', sa.String(), nullable=False),
    sa.Column('signer_email', sa.String(), nullable=False),
    sa.Column('signer_document_number', sa.String(), nullable=True),
    sa.Column('document_hash_sha256', sa.String(), nullable=False),
    sa.Column('signature_level', sa.String(), nullable=False),
    sa.Column('psc_provider', sa.String(), nullable=True),
    sa.Column('psc_certificate_serial', sa.String(), nullable=True),
    sa.Column('padres_applied', sa.Boolean(), nullable=True),
    sa.Column('timestamp_token', sa.Text(), nullable=True),
    sa.Column('signed_document_storage_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signer_ip', sa.String(), nullable=True),
    sa.Column('signer_user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('unit_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_events')
    op.drop_table('signature_requests')
    op.drop_table('payments')
    op.drop_table('kyc_verifications')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    op.drop_table('pilot_leads')
    op.drop_table('clients')
    # ### end Alembic commands ###
